id: I6BD2168B
default_language: de
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:44.816945
last_modified: 2023-01-04 11:28:44.816976
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  2F43:
    title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
    base_file: 2F43.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
